### ISSUE TITLE
Claiming issue

### ISSUE THREAD

**Issue by 1WiseFoxx** [DatOneLefty/territory.cf#14]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7201994-268989648_2-s1-v1.png?transparent=1&palette=1&width=246)
Sometimes, the territory I claim is reset back to what it was. Please fix...
![bitmoji](https://render.bitstrips.com/v2/cpanel/10219223-268989648_2-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by lholliger** [comment]
fixed with local cache and new server setup
