### ISSUE TITLE
Alliances!

### ISSUE THREAD

**Issue by 1WiseFoxx** [DatOneLefty/territory.cf#15]
Hello! I have an idea that Lefty and I came up with. It is called Alliances! In it, on territory, you can team up with other players. You can't take their territory, and they can't take yours. Basically, it is whitelisting a player.
![bitmoji](https://render.bitstrips.com/v2/cpanel/10217268-268989648_3-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by lholliger** [comment]
owait i added this
