### ISSUE TITLE
Chunk loading ERROR [URGENT]

### ISSUE THREAD

**Issue by 1WiseFoxx** [DatOneLefty/territory.cf#17]
The map chunk loading is SUPER glitchy. While moving around my territory (holding down any WASD key), the map chunk loading fails and my territory disappears! Please fix.

**Comment by lholliger** [comment]
problem confirmed and will be fixed as fast as possible. The server will be rolled back to a previous update that didnt have this issue

**Comment by lholliger** [comment]
fixed, issue was how it was reading the array
