### ISSUE TITLE
mixed tabs and spaces

### ISSUE THREAD

**Issue by bates64** [DatOneLefty/territory.cf#9]
</3

**Comment by lholliger** [comment]
what part of the project needs to be fixed?

**Comment by lholliger** [comment]
Will reopen when more info is provided

**Comment by ghost** [comment]
The code is not consistent.  Different parts of the files have spaces instead of tabs and it looks weird

**Comment by lholliger** [comment]
It doesn't directly cause issues with the program, but I'll add it ti my long list of things to do over the weekend

**Comment by lholliger** [comment]
fixed with latest commit
